### ISSUE TITLE
Killing container process results in panic for podman ps --all command

### ISSUE THREAD

**Issue by sunilcio** [projectatomic/libpod#395]
After experiencing the lock issue described in https://github.com/projectatomic/libpod/pull/394 , I manually killed the process running inside container along with `conmon` and `runc` process.

Now if I run `podman ps --all`, it gives below panic.
```
# podman ps -a
panic: runtime error: index out of range

goroutine 1 [running]:
main.generatePsOutput(0xc42000e3c8, 0x1, 0x1, 0x1, 0x0, 0x0, 0x22d3af8, 0x57, 0xffffffffffffffff, 0x0, ...)
	/builddir/build/BUILD/libpod-3723cecc33399629408770e44eb363e9ca36fdce/_build/src/github.com/projectatomic/libpod/cmd/podman/ps.go:634 +0x43e
main.psCmd(0xc4200b7080, 0x0, 0x0)
	/builddir/build/BUILD/libpod-3723cecc33399629408770e44eb363e9ca36fdce/_build/src/github.com/projectatomic/libpod/cmd/podman/ps.go:217 +0x5a6
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0x1f3ae80, 0x2311138, 0xc4200b7080, 0x0, 0xc420067200)
	/builddir/build/BUILD/libpod-3723cecc33399629408770e44eb363e9ca36fdce/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x225b5a0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x226ade3, 0xf, 0x0, ...)
	/builddir/build/BUILD/libpod-3723cecc33399629408770e44eb363e9ca36fdce/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x505
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc420012700, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
	/builddir/build/BUILD/libpod-3723cecc33399629408770e44eb363e9ca36fdce/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x740
main.main()
	/builddir/build/BUILD/libpod-3723cecc33399629408770e44eb363e9ca36fdce/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:155 +0x11a5
````

- Checking `containers.json`, I see the container `quirky_meninsky` which I killed:
```
# cat /var/lib/containers/storage/overlay-containers/containers.json  | python3 -mjson.tool
[
    {
        "id": "0e5a44ce2c720a78ba5af9c98b05f70d26cba65c9a4b8897804270151185e437",
        "names": [
            "alpine"
        ],
        "image": "3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353",
        "layer": "e2679ef93a586b744f08c5a95394acfd7b9592f1e8c8b1b95070dee04a8868d5",
        "metadata": "{\"image-name\":\"alpine\",\"image-id\":\"3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353\",\"name\":\"alpine\",\"created-at\":1518882862,\"mountlabel\":\"system_u:object_r:container_file_t:s0:c738,c849\"}",
        "created": "2018-02-17T15:54:22.297826811Z"
    },
    {
        "id": "3f7f4ccd9a060a2750f07e13acfd3adb22157a3589f3d0d5716e0adf34a141d0",
        "names": [
            "infallible_engelbart"
        ],
        "image": "3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353",
        "layer": "d4a6dc0b97a60ab9eaf19527a73f276fb30ba40fce72b6460eb6046e80cb601d",
        "metadata": "{\"image-name\":\"alpine\",\"image-id\":\"3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353\",\"name\":\"infallible_engelbart\",\"created-at\":1518883262,\"mountlabel\":\"system_u:object_r:container_file_t:s0:c122,c694\"}",
        "created": "2018-02-17T16:01:02.81512247Z"
    },
    {
        "id": "9c0d778fcb7e3889bb81f86686344e7b5e205fe7b7165916050629ba31136b28",
        "names": [
            "festive_khorana"
        ],
        "image": "3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353",
        "layer": "ebd0ce29e031f7093cf7ed0ebe8705b9bca2dfd9fe56d1eebab566a61199377d",
        "metadata": "{\"image-name\":\"alpine\",\"image-id\":\"3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353\",\"name\":\"festive_khorana\",\"created-at\":1518884468,\"mountlabel\":\"system_u:object_r:container_file_t:s0:c373,c435\"}",
        "created": "2018-02-17T16:21:08.842861953Z"
    },
    {
        "id": "ff67fb184d21d9862d4bd10e77ad6e05db61790c6085c30741b6ba1c47bf5220",
        "names": [
            "quirky_meninsky"
        ],
        "image": "3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353",
        "layer": "22f23cb02178669d439f5d2353baa84ac28a1449e3bd20c71dee4a66484bb81b",
        "metadata": "{\"image-name\":\"alpine\",\"image-id\":\"3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353\",\"name\":\"quirky_meninsky\",\"created-at\":1519401372,\"mountlabel\":\"system_u:object_r:container_file_t:s0:c112,c815\"}",
        "created": "2018-02-23T15:56:12.072040967Z"
    }
]
```

**Comment by sunilcio** [comment]
With below `podman` version, I no longer see panic after running `podman ps -a` in above condition.
```
# podman version
Version:       0.2.3-dev
Go Version:    go1.9.4
Git Commit:    "656840c9924b0348c7e939b4215f14c5b076842f"
Built:         Fri Mar  2 09:47:14 2018
OS/Arch:       linux/amd64
```
So I see the panic issue is fixed.

**Comment by mheon** [comment]
Panic should be handled, so closing
