### ISSUE TITLE
podman load: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#403]
[Warning: please don't run arbitrary commands with unknown data just on my say-so]

The attached tgz, when gunzip'ed, causes a crash in `podman load`:
```
# podman load -i  /tmp/load_test_out.tar
panic: runtime error: index out of range
        
goroutine 1 [running]:
github.com/projectatomic/libpod/libpod.(*Runtime).getPullListFromRef(0xc4204a4c00, 0x34b8d20, 0xc420366ca0, 0xc4201c8660, 0x25, 0xc420599d40, 0xc420369e00, 0xc4201c8660, 0xc4206a10a0, 0x456c9f, ...)
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/libpod/runtime_img.go:627 +0xd5c
github.com/projectatomic/libpod/libpod.(*Runtime).PullImage(0xc4204a4c00, 0xc4201c8660, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...
)
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/libpod/runtime_img.go:701 +0x94d
main.loadCmd(0xc4201a3340, 0x0, 0x0)
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/cmd/podman/load.go:105 +0x2f4
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0x1f411a0, 0x23182b0, 0xc4201a3340, 0x0, 0xc420263260)
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x2263500, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x228d5fb, 0x21, 0x0, ...)
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x505
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc4200dc380, 0xc4200100c0, 0x4, 0x4, 0x0, 0x0)
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x740
main.main()
        /builddir/build/BUILD/libpod-525e3b17e4723afeebf45a1a24f00b2af17ddedf/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:155 +0x11a5
```

podman is 0.2.2-1.git525e3b1.fc27.x86_64.

Context: the tarball is a modification of [this one](https://github.com/autotest/autotest-docker/blob/master/subtests/docker_cli/load/load_test.tar.gz) used in docker-autotest; I don't know its provenance beyond that. The linked-to tarball doesn't include `manifest.json`, so the one I've attached is the result of `docker load -i load_test.tar.gz` then `docker save 5a989dd2c48f >/tmp/load_test_out.tar`. But again, don't just take my word for it. 

(And hey, out of curiosity, should `podman load` be able to handle gzip'ed tar? docker does.)

Attached: [load_test_out.tar.gz](https://github.com/projectatomic/libpod/files/1759565/load_test_out.tar.gz)

**Comment by baude** [comment]
@edsantiago I'm to have a PR for this soon.  The gzip part I am going to log into another issue and copy you on.  I need to talk to Nalind before I propose a fix for that.  My PR should solve the panic sans gz.
