### ISSUE TITLE
podman run /nonesuch : panic (0.3.4)

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#553]
podman-0.3.4-1.git57b403e.fc27.x86_64

```
# podman run /slartibartfast
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa9ef2a]

goroutine 1 [running]:
github.com/projectatomic/libpod/libpod/image.(*Image).toImageRef(0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/libpod/image/image.go:460 +0x3a
github.com/projectatomic/libpod/libpod/image.(*Image).ociv1Image(0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/libpod/image/image.go:562 +0x2f
github.com/projectatomic/libpod/libpod/image.(*Image).Inspect(0x0, 0x7ffd5b470f98, 0xf, 0x0)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/libpod/image/image.go:590 +0x43
main.runCmd(0xc420052000, 0x0, 0x0)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/cmd/podman/run.go:60 +0x215
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0x1f27020, 0x22f9cf8, 0xc420052000, 0x0, 0xc4203d13e0)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x22439bc, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x226c876, 0x20, 0
x0, ...)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x505
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc420094e00, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x740
main.main()
        /builddir/build/BUILD/libpod-57b403eda155d321d8aa29cfa0085aac8ce28a57/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:156 +0x11e3
```
Expected: a friendlier message without so much SEGV

FWIW podman-0.3.3-2.gitb47fc0d.fc27.x86_64's error is:
```
error getting storage image "/slartibartfast": error parsing reference to image "/:": error parsing named reference "/:": invalid reference format
```

**Comment by rhatdan** [comment]
This is definitely up @baude alley.

**Comment by baude** [comment]
@edsantiago just to be sure, /slartibartfast is meant to refer to a  bogus image name correct?

**Comment by edsantiago** [comment]
It's just copy/paste. Yes. Without the slash, I get 'Trying to pull', then Failed, then a similar panic.
