### ISSUE TITLE
podman run image-committed-without-a-name : panic

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#587]
I don't know if this is a problem in `run` or in `commit`. 
```
# podman run --name foo fedora date
Apr  3 15:05:07 UTC 2018
# cid=$(podman commit --quiet foo)
# podman run $cid                          
panic: runtime error: index out of range                          

goroutine 1 [running]:           
main.runCmd(0xc4200b6f20, 0x0, 0x0)                               
        /builddir/build/BUILD/libpod-db6bf9e3ad7900f0bf062fd12b80706c1bd7bb5f/_build/src/github.com/projectatomic/libpod/cmd/podman/run.go:68 +0x1d06                
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0xfa3400, 0x119e868, 0xc4200b6f20, 0x0, 0xc4200651a0)     
        /builddir/build/BUILD/libpod-db6bf9e3ad7900f0bf062fd12b80706c1bd7bb5f/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xd2                                
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x11244b1, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1143be6, 0x20, 0x0, ...)                         
        /builddir/build/BUILD/libpod-db6bf9e3ad7900f0bf062fd12b80706c1bd7bb5f/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x505                           
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc4200dca80, 0xc420010090, 0x3, 0x3, 0x0, 0x0)             
        /builddir/build/BUILD/libpod-db6bf9e3ad7900f0bf062fd12b80706c1bd7bb5f/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x740                               
main.main()                      
        /builddir/build/BUILD/libpod-db6bf9e3ad7900f0bf062fd12b80706c1bd7bb5f/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:156 +0x11e3              
```
Feeding it an image name (podman commit --quiet foo **bar**) eliminates this, but see #586 for a separate problem.

podman-0.3.5-1.gitdb6bf9e.fc27.x86_64

**Comment by mheon** [comment]
That's an index out of range in `podman run`, so we have at a minimum a bug in `run`. There could also be a bug in commit (outputting bad IDs?) to trigger that bug in run.
