### ISSUE TITLE
Panic: `podman varlink foo` gives runtime error.

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/libpod#888]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**
panic: runtime error: index out of range, should be handled and might be ignored if command argument is not as expected.

**Steps to reproduce the issue:**

```
$ sudo dnf --enablerepo updates-testing update podman

$ podman version
Version:       0.6.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64

$ podman varlink foo
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/projectatomic/libpod/vendor/github.com/varlink/go/varlink.(*Service).parseAddress(0xc4200ecbb0, 0x7ffc9bec27b9, 0x6, 0xc4202ee290, 0xc4201d8dc0)
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/vendor/github.com/varlink/go/varlink/service.go:202 +0x21f
github.com/projectatomic/libpod/vendor/github.com/varlink/go/varlink.(*Service).Listen(0xc4200ecbb0, 0x7ffc9bec27b9, 0x6, 0x3b9aca00, 0x0, 0x0)
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/vendor/github.com/varlink/go/varlink/service.go:272 +0xf2
main.varlinkCmd(0xc4201342c0, 0xc4201d8b00, 0xc4201342c0)
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/cmd/podman/varlink.go:64 +0x290
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0xfdf4a0, 0x12099e0, 0xc4201342c0, 0x0, 0xc4204c21e0)
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x1182853, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1190fd5, 0x15, 0x0, ...)
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x4c7
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc42019ea80, 0xc4200b6060, 0x3, 0x3, 0x0, 0x0)
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
	/builddir/build/BUILD/libpod-3e0ff127c2210cc54681a776e12d8f1d3ae66630/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:174 +0x141f

```

**Comment by vrothberg** [comment]
I had a look at the code and it turns out to be an issue of `varlink/go`, in particular, the last call we see in the stack trace: https://github.com/varlink/go/blob/master/varlink/service.go#L199

I will open an issue for `varlink/go` and suggest to keep this issue here open until a fixed `valink/go` can be vendored.
